/********************************************************************************
** Form generated from reading UI file 'mainwidget.ui'
**
** Created by: Qt User Interface Compiler version 6.1.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWIDGET_H
#define UI_MAINWIDGET_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWidget
{
public:
    QStatusBar *statusbar;
    QGroupBox *vzaimode;
    QRadioButton *plant_b;
    QRadioButton *delete_b;
    QRadioButton *infoplant_b;
    QRadioButton *infodirt_b;
    QGroupBox *timemode;
    QRadioButton *normal_b;
    QRadioButton *speed_b;
    QRadioButton *pause_b;
    QLabel *pogoda;
    QFrame *place;
    QGroupBox *type_plant;
    QRadioButton *grass_type;
    QRadioButton *bush_type;
    QRadioButton *tree_type;
    QGroupBox *info_type;
    QLabel *info_1;
    QLabel *info_2;
    QLabel *info_3;
    QLabel *info_4;
    QLabel *info_6;
    QLabel *info_7;
    QLabel *info_8;
    QLabel *info_9;
    QLabel *info_5;
    QLabel *info_10;
    QLabel *info_11;
    QLabel *info_12;
    QLabel *info_0;
    QLabel *info_13;
    QLabel *info_00;
    QGroupBox *info_value;
    QLabel *i_1;
    QLabel *i_2;
    QLabel *i_3;
    QLabel *i_4;
    QLabel *i_6;
    QLabel *i_7;
    QLabel *i_8;
    QLabel *i_9;
    QLabel *i_5;
    QLabel *i_10;
    QLabel *i_11;
    QLabel *i_12;
    QLabel *i_0;
    QLabel *i_13;
    QLabel *i_00;
    QLabel *info_name;
    QLabel *info_weather;
    QGroupBox *info_wvalue;
    QLabel *w_1;
    QLabel *w_2;
    QLabel *w_3;
    QLabel *w_0;
    QGroupBox *info_wtype;
    QLabel *winfo_1;
    QLabel *winfo_2;
    QLabel *winfo_3;
    QLabel *winfo_0;
    QGroupBox *info_ftype;
    QLabel *finfo_1;
    QLabel *finfo_2;
    QLabel *finfo_3;
    QLabel *finfo_0;
    QLabel *info_forest;
    QGroupBox *info_fvalue;
    QLabel *fi_1;
    QLabel *fi_2;
    QLabel *fi_3;
    QLabel *fi_0;
    QLabel *label;
    QLabel *label_2;
    QLabel *all_time_text;

    void setupUi(QWidget *MainWidget)
    {
        if (MainWidget->objectName().isEmpty())
            MainWidget->setObjectName(QString::fromUtf8("MainWidget"));
        MainWidget->resize(1359, 699);
        MainWidget->setMinimumSize(QSize(1359, 699));
        QIcon icon;
        icon.addFile(QString::fromUtf8("icon.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWidget->setWindowIcon(icon);
        statusbar = new QStatusBar(MainWidget);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        statusbar->setGeometry(QRect(0, 0, 3, 18));
        vzaimode = new QGroupBox(MainWidget);
        vzaimode->setObjectName(QString::fromUtf8("vzaimode"));
        vzaimode->setGeometry(QRect(830, 20, 181, 111));
        vzaimode->setStyleSheet(QString::fromUtf8("background-color:rgb(255, 227, 187);"));
        plant_b = new QRadioButton(vzaimode);
        plant_b->setObjectName(QString::fromUtf8("plant_b"));
        plant_b->setGeometry(QRect(10, 20, 111, 17));
        plant_b->setChecked(true);
        delete_b = new QRadioButton(vzaimode);
        delete_b->setObjectName(QString::fromUtf8("delete_b"));
        delete_b->setGeometry(QRect(10, 40, 121, 17));
        infoplant_b = new QRadioButton(vzaimode);
        infoplant_b->setObjectName(QString::fromUtf8("infoplant_b"));
        infoplant_b->setGeometry(QRect(10, 60, 121, 17));
        infodirt_b = new QRadioButton(vzaimode);
        infodirt_b->setObjectName(QString::fromUtf8("infodirt_b"));
        infodirt_b->setGeometry(QRect(10, 80, 101, 17));
        timemode = new QGroupBox(MainWidget);
        timemode->setObjectName(QString::fromUtf8("timemode"));
        timemode->setGeometry(QRect(830, 240, 181, 91));
        timemode->setStyleSheet(QString::fromUtf8("background-color: rgb(205, 208, 255);"));
        normal_b = new QRadioButton(timemode);
        normal_b->setObjectName(QString::fromUtf8("normal_b"));
        normal_b->setGeometry(QRect(10, 20, 91, 17));
        normal_b->setChecked(true);
        speed_b = new QRadioButton(timemode);
        speed_b->setObjectName(QString::fromUtf8("speed_b"));
        speed_b->setGeometry(QRect(10, 40, 91, 17));
        pause_b = new QRadioButton(timemode);
        pause_b->setObjectName(QString::fromUtf8("pause_b"));
        pause_b->setGeometry(QRect(10, 60, 82, 17));
        pogoda = new QLabel(MainWidget);
        pogoda->setObjectName(QString::fromUtf8("pogoda"));
        pogoda->setGeometry(QRect(1278, 20, 70, 70));
        pogoda->setScaledContents(true);
        place = new QFrame(MainWidget);
        place->setObjectName(QString::fromUtf8("place"));
        place->setEnabled(true);
        place->setGeometry(QRect(20, 20, 800, 600));
        place->setStyleSheet(QString::fromUtf8("background-color: rgb(47, 28, 11)"));
        place->setFrameShape(QFrame::StyledPanel);
        place->setFrameShadow(QFrame::Raised);
        type_plant = new QGroupBox(MainWidget);
        type_plant->setObjectName(QString::fromUtf8("type_plant"));
        type_plant->setGeometry(QRect(830, 140, 181, 91));
        type_plant->setStyleSheet(QString::fromUtf8("background-color: rgb(204, 255, 188);"));
        grass_type = new QRadioButton(type_plant);
        grass_type->setObjectName(QString::fromUtf8("grass_type"));
        grass_type->setGeometry(QRect(10, 20, 111, 17));
        grass_type->setChecked(true);
        bush_type = new QRadioButton(type_plant);
        bush_type->setObjectName(QString::fromUtf8("bush_type"));
        bush_type->setGeometry(QRect(10, 40, 121, 17));
        tree_type = new QRadioButton(type_plant);
        tree_type->setObjectName(QString::fromUtf8("tree_type"));
        tree_type->setGeometry(QRect(10, 60, 121, 17));
        info_type = new QGroupBox(MainWidget);
        info_type->setObjectName(QString::fromUtf8("info_type"));
        info_type->setGeometry(QRect(830, 360, 161, 331));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 127, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 254, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(255, 255, 190, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(127, 127, 63, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(170, 170, 85, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(255, 255, 191, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush9(QColor(0, 0, 0, 128));
        brush9.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        info_type->setPalette(palette);
        info_type->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        info_type->setFlat(false);
        info_1 = new QLabel(info_type);
        info_1->setObjectName(QString::fromUtf8("info_1"));
        info_1->setGeometry(QRect(10, 60, 148, 16));
        QFont font;
        font.setFamilies({QString::fromUtf8("Consolas")});
        info_1->setFont(font);
        info_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_2 = new QLabel(info_type);
        info_2->setObjectName(QString::fromUtf8("info_2"));
        info_2->setGeometry(QRect(10, 80, 148, 16));
        info_2->setFont(font);
        info_2->setStyleSheet(QString::fromUtf8(""));
        info_3 = new QLabel(info_type);
        info_3->setObjectName(QString::fromUtf8("info_3"));
        info_3->setGeometry(QRect(10, 100, 148, 16));
        info_3->setFont(font);
        info_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_4 = new QLabel(info_type);
        info_4->setObjectName(QString::fromUtf8("info_4"));
        info_4->setGeometry(QRect(10, 120, 148, 16));
        info_4->setFont(font);
        info_4->setStyleSheet(QString::fromUtf8(""));
        info_6 = new QLabel(info_type);
        info_6->setObjectName(QString::fromUtf8("info_6"));
        info_6->setGeometry(QRect(10, 160, 148, 16));
        info_6->setFont(font);
        info_6->setStyleSheet(QString::fromUtf8(""));
        info_7 = new QLabel(info_type);
        info_7->setObjectName(QString::fromUtf8("info_7"));
        info_7->setGeometry(QRect(10, 180, 148, 16));
        info_7->setFont(font);
        info_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_8 = new QLabel(info_type);
        info_8->setObjectName(QString::fromUtf8("info_8"));
        info_8->setGeometry(QRect(10, 200, 148, 16));
        info_8->setFont(font);
        info_8->setStyleSheet(QString::fromUtf8(""));
        info_9 = new QLabel(info_type);
        info_9->setObjectName(QString::fromUtf8("info_9"));
        info_9->setGeometry(QRect(10, 220, 148, 16));
        info_9->setFont(font);
        info_9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_5 = new QLabel(info_type);
        info_5->setObjectName(QString::fromUtf8("info_5"));
        info_5->setGeometry(QRect(10, 140, 148, 16));
        info_5->setFont(font);
        info_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_10 = new QLabel(info_type);
        info_10->setObjectName(QString::fromUtf8("info_10"));
        info_10->setGeometry(QRect(10, 240, 148, 16));
        info_10->setFont(font);
        info_10->setStyleSheet(QString::fromUtf8(""));
        info_11 = new QLabel(info_type);
        info_11->setObjectName(QString::fromUtf8("info_11"));
        info_11->setGeometry(QRect(10, 260, 148, 16));
        info_11->setFont(font);
        info_11->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_12 = new QLabel(info_type);
        info_12->setObjectName(QString::fromUtf8("info_12"));
        info_12->setGeometry(QRect(10, 280, 148, 16));
        info_12->setFont(font);
        info_12->setStyleSheet(QString::fromUtf8(""));
        info_0 = new QLabel(info_type);
        info_0->setObjectName(QString::fromUtf8("info_0"));
        info_0->setGeometry(QRect(10, 40, 148, 16));
        info_0->setFont(font);
        info_0->setStyleSheet(QString::fromUtf8(""));
        info_13 = new QLabel(info_type);
        info_13->setObjectName(QString::fromUtf8("info_13"));
        info_13->setGeometry(QRect(10, 300, 148, 16));
        info_13->setFont(font);
        info_13->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_00 = new QLabel(info_type);
        info_00->setObjectName(QString::fromUtf8("info_00"));
        info_00->setGeometry(QRect(10, 20, 148, 16));
        info_00->setFont(font);
        info_00->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_value = new QGroupBox(MainWidget);
        info_value->setObjectName(QString::fromUtf8("info_value"));
        info_value->setGeometry(QRect(990, 360, 131, 331));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        info_value->setPalette(palette1);
        info_value->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        info_value->setFlat(false);
        i_1 = new QLabel(info_value);
        i_1->setObjectName(QString::fromUtf8("i_1"));
        i_1->setGeometry(QRect(3, 60, 125, 16));
        i_1->setFont(font);
        i_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        i_2 = new QLabel(info_value);
        i_2->setObjectName(QString::fromUtf8("i_2"));
        i_2->setGeometry(QRect(3, 80, 125, 16));
        i_2->setFont(font);
        i_2->setStyleSheet(QString::fromUtf8(""));
        i_3 = new QLabel(info_value);
        i_3->setObjectName(QString::fromUtf8("i_3"));
        i_3->setGeometry(QRect(3, 100, 125, 16));
        i_3->setFont(font);
        i_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        i_4 = new QLabel(info_value);
        i_4->setObjectName(QString::fromUtf8("i_4"));
        i_4->setGeometry(QRect(3, 120, 125, 16));
        i_4->setFont(font);
        i_4->setStyleSheet(QString::fromUtf8(""));
        i_6 = new QLabel(info_value);
        i_6->setObjectName(QString::fromUtf8("i_6"));
        i_6->setGeometry(QRect(3, 160, 125, 16));
        i_6->setFont(font);
        i_6->setStyleSheet(QString::fromUtf8(""));
        i_7 = new QLabel(info_value);
        i_7->setObjectName(QString::fromUtf8("i_7"));
        i_7->setGeometry(QRect(3, 180, 125, 16));
        i_7->setFont(font);
        i_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        i_8 = new QLabel(info_value);
        i_8->setObjectName(QString::fromUtf8("i_8"));
        i_8->setGeometry(QRect(3, 200, 125, 16));
        i_8->setFont(font);
        i_8->setStyleSheet(QString::fromUtf8(""));
        i_9 = new QLabel(info_value);
        i_9->setObjectName(QString::fromUtf8("i_9"));
        i_9->setGeometry(QRect(3, 220, 125, 16));
        i_9->setFont(font);
        i_9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        i_5 = new QLabel(info_value);
        i_5->setObjectName(QString::fromUtf8("i_5"));
        i_5->setGeometry(QRect(3, 140, 125, 16));
        i_5->setFont(font);
        i_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        i_10 = new QLabel(info_value);
        i_10->setObjectName(QString::fromUtf8("i_10"));
        i_10->setGeometry(QRect(3, 240, 125, 16));
        i_10->setFont(font);
        i_10->setStyleSheet(QString::fromUtf8(""));
        i_11 = new QLabel(info_value);
        i_11->setObjectName(QString::fromUtf8("i_11"));
        i_11->setGeometry(QRect(3, 260, 125, 16));
        i_11->setFont(font);
        i_11->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        i_12 = new QLabel(info_value);
        i_12->setObjectName(QString::fromUtf8("i_12"));
        i_12->setGeometry(QRect(3, 280, 125, 16));
        i_12->setFont(font);
        i_12->setStyleSheet(QString::fromUtf8(""));
        i_0 = new QLabel(info_value);
        i_0->setObjectName(QString::fromUtf8("i_0"));
        i_0->setGeometry(QRect(3, 40, 125, 16));
        i_0->setFont(font);
        i_0->setStyleSheet(QString::fromUtf8(""));
        i_13 = new QLabel(info_value);
        i_13->setObjectName(QString::fromUtf8("i_13"));
        i_13->setGeometry(QRect(3, 300, 125, 16));
        i_13->setFont(font);
        i_13->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        i_00 = new QLabel(info_value);
        i_00->setObjectName(QString::fromUtf8("i_00"));
        i_00->setGeometry(QRect(3, 20, 125, 16));
        i_00->setFont(font);
        i_00->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_name = new QLabel(MainWidget);
        info_name->setObjectName(QString::fromUtf8("info_name"));
        info_name->setGeometry(QRect(831, 340, 291, 20));
        info_name->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        info_name->setTextFormat(Qt::PlainText);
        info_weather = new QLabel(MainWidget);
        info_weather->setObjectName(QString::fromUtf8("info_weather"));
        info_weather->setGeometry(QRect(1021, 20, 251, 20));
        info_weather->setStyleSheet(QString::fromUtf8("background-color: rgb(245, 205, 255);"));
        info_weather->setTextFormat(Qt::PlainText);
        info_wvalue = new QGroupBox(MainWidget);
        info_wvalue->setObjectName(QString::fromUtf8("info_wvalue"));
        info_wvalue->setGeometry(QRect(1170, 40, 101, 121));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush10(QColor(245, 205, 255, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        info_wvalue->setPalette(palette2);
        info_wvalue->setStyleSheet(QString::fromUtf8("background-color: rgb(245, 205, 255);"));
        info_wvalue->setFlat(false);
        w_1 = new QLabel(info_wvalue);
        w_1->setObjectName(QString::fromUtf8("w_1"));
        w_1->setGeometry(QRect(3, 35, 95, 16));
        w_1->setFont(font);
        w_2 = new QLabel(info_wvalue);
        w_2->setObjectName(QString::fromUtf8("w_2"));
        w_2->setGeometry(QRect(3, 55, 95, 16));
        w_2->setFont(font);
        w_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        w_3 = new QLabel(info_wvalue);
        w_3->setObjectName(QString::fromUtf8("w_3"));
        w_3->setGeometry(QRect(3, 75, 95, 16));
        w_3->setFont(font);
        w_0 = new QLabel(info_wvalue);
        w_0->setObjectName(QString::fromUtf8("w_0"));
        w_0->setGeometry(QRect(3, 15, 95, 16));
        w_0->setFont(font);
        w_0->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_wtype = new QGroupBox(MainWidget);
        info_wtype->setObjectName(QString::fromUtf8("info_wtype"));
        info_wtype->setGeometry(QRect(1020, 40, 150, 121));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush10);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush10);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        info_wtype->setPalette(palette3);
        info_wtype->setStyleSheet(QString::fromUtf8("background-color: rgb(245, 205, 255);"));
        info_wtype->setFlat(false);
        winfo_1 = new QLabel(info_wtype);
        winfo_1->setObjectName(QString::fromUtf8("winfo_1"));
        winfo_1->setGeometry(QRect(10, 35, 137, 16));
        winfo_1->setFont(font);
        winfo_2 = new QLabel(info_wtype);
        winfo_2->setObjectName(QString::fromUtf8("winfo_2"));
        winfo_2->setGeometry(QRect(10, 55, 137, 16));
        winfo_2->setFont(font);
        winfo_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        winfo_3 = new QLabel(info_wtype);
        winfo_3->setObjectName(QString::fromUtf8("winfo_3"));
        winfo_3->setGeometry(QRect(10, 75, 137, 16));
        winfo_3->setFont(font);
        winfo_0 = new QLabel(info_wtype);
        winfo_0->setObjectName(QString::fromUtf8("winfo_0"));
        winfo_0->setGeometry(QRect(10, 15, 137, 16));
        winfo_0->setFont(font);
        winfo_0->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_ftype = new QGroupBox(MainWidget);
        info_ftype->setObjectName(QString::fromUtf8("info_ftype"));
        info_ftype->setGeometry(QRect(1020, 190, 150, 121));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush11(QColor(167, 255, 215, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        info_ftype->setPalette(palette4);
        info_ftype->setStyleSheet(QString::fromUtf8("background-color: rgb(167, 255, 215);"));
        info_ftype->setFlat(false);
        finfo_1 = new QLabel(info_ftype);
        finfo_1->setObjectName(QString::fromUtf8("finfo_1"));
        finfo_1->setGeometry(QRect(10, 35, 137, 16));
        finfo_1->setFont(font);
        finfo_2 = new QLabel(info_ftype);
        finfo_2->setObjectName(QString::fromUtf8("finfo_2"));
        finfo_2->setGeometry(QRect(10, 55, 137, 16));
        finfo_2->setFont(font);
        finfo_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        finfo_3 = new QLabel(info_ftype);
        finfo_3->setObjectName(QString::fromUtf8("finfo_3"));
        finfo_3->setGeometry(QRect(10, 75, 137, 16));
        finfo_3->setFont(font);
        finfo_0 = new QLabel(info_ftype);
        finfo_0->setObjectName(QString::fromUtf8("finfo_0"));
        finfo_0->setGeometry(QRect(10, 15, 137, 16));
        finfo_0->setFont(font);
        finfo_0->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        info_forest = new QLabel(MainWidget);
        info_forest->setObjectName(QString::fromUtf8("info_forest"));
        info_forest->setGeometry(QRect(1021, 170, 251, 20));
        info_forest->setStyleSheet(QString::fromUtf8("background-color: rgb(167, 255, 215);"));
        info_forest->setTextFormat(Qt::PlainText);
        info_fvalue = new QGroupBox(MainWidget);
        info_fvalue->setObjectName(QString::fromUtf8("info_fvalue"));
        info_fvalue->setGeometry(QRect(1170, 190, 101, 121));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        info_fvalue->setPalette(palette5);
        info_fvalue->setStyleSheet(QString::fromUtf8("background-color: rgb(167, 255, 215);"));
        info_fvalue->setFlat(false);
        fi_1 = new QLabel(info_fvalue);
        fi_1->setObjectName(QString::fromUtf8("fi_1"));
        fi_1->setGeometry(QRect(3, 35, 95, 16));
        fi_1->setFont(font);
        fi_2 = new QLabel(info_fvalue);
        fi_2->setObjectName(QString::fromUtf8("fi_2"));
        fi_2->setGeometry(QRect(3, 55, 95, 16));
        fi_2->setFont(font);
        fi_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        fi_3 = new QLabel(info_fvalue);
        fi_3->setObjectName(QString::fromUtf8("fi_3"));
        fi_3->setGeometry(QRect(3, 75, 95, 16));
        fi_3->setFont(font);
        fi_0 = new QLabel(info_fvalue);
        fi_0->setObjectName(QString::fromUtf8("fi_0"));
        fi_0->setGeometry(QRect(3, 15, 95, 16));
        fi_0->setFont(font);
        fi_0->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label = new QLabel(MainWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 630, 151, 16));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        QBrush brush12(QColor(127, 127, 127, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush12);
        QBrush brush13(QColor(170, 170, 170, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        label->setPalette(palette6);
        label_2 = new QLabel(MainWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 650, 151, 16));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        label_2->setPalette(palette7);
        all_time_text = new QLabel(MainWidget);
        all_time_text->setObjectName(QString::fromUtf8("all_time_text"));
        all_time_text->setGeometry(QRect(20, 1, 691, 16));

        retranslateUi(MainWidget);

        QMetaObject::connectSlotsByName(MainWidget);
    } // setupUi

    void retranslateUi(QWidget *MainWidget)
    {
        MainWidget->setWindowTitle(QCoreApplication::translate("MainWidget", "\320\240\320\260\321\201\321\202\320\270\321\202\320\265\320\273\321\214\320\275\320\276\320\265 \321\201\320\276\320\276\320\261\321\211\320\265\321\201\321\202\320\262\320\276", nullptr));
        vzaimode->setTitle(QCoreApplication::translate("MainWidget", "\320\240\320\265\320\266\320\270\320\274 \320\262\320\267\320\260\320\270\320\274\320\276\320\264\320\265\320\271\321\201\321\202\320\262\320\270\321\217", nullptr));
        plant_b->setText(QCoreApplication::translate("MainWidget", "\320\241\320\260\320\264\320\270\321\202\321\214 \321\200\320\260\321\201\321\202\320\265\320\275\320\270\320\265", nullptr));
        delete_b->setText(QCoreApplication::translate("MainWidget", "\320\243\320\264\320\260\320\273\320\270\321\202\321\214 \321\200\320\260\321\201\321\202\320\265\320\275\320\270\320\265", nullptr));
        infoplant_b->setText(QCoreApplication::translate("MainWidget", "\320\230\320\275\321\204\320\276 \320\276 \321\200\320\260\321\201\321\202\320\265\320\275\320\270\320\270", nullptr));
        infodirt_b->setText(QCoreApplication::translate("MainWidget", "\320\230\320\275\321\204\320\276 \320\276 \320\277\320\276\321\207\320\262\320\265", nullptr));
        timemode->setTitle(QCoreApplication::translate("MainWidget", "\320\240\320\265\320\266\320\270\320\274 \320\262\321\200\320\265\320\274\320\265\320\275\320\270", nullptr));
        normal_b->setText(QCoreApplication::translate("MainWidget", "\320\235\320\276\321\200\320\274\320\260\320\273\321\214\320\275\321\213\320\271", nullptr));
        speed_b->setText(QCoreApplication::translate("MainWidget", "\320\243\321\201\320\272\320\276\321\200\320\265\320\275\320\275\321\213\320\271", nullptr));
        pause_b->setText(QCoreApplication::translate("MainWidget", "\320\237\320\260\321\203\320\267\320\260", nullptr));
        pogoda->setText(QString());
        type_plant->setTitle(QCoreApplication::translate("MainWidget", "\320\222\320\270\320\264 \321\200\320\260\321\201\321\202\320\265\320\275\320\270\321\217 \320\264\320\273\321\217 \320\277\320\276\321\201\320\260\320\264\320\272\320\270", nullptr));
        grass_type->setText(QCoreApplication::translate("MainWidget", "\320\235\320\276\320\262\320\260\321\217 \321\202\321\200\320\260\320\262\320\260", nullptr));
        bush_type->setText(QCoreApplication::translate("MainWidget", "\320\235\320\276\320\262\321\213\320\271 \320\272\321\203\321\201\321\202", nullptr));
        tree_type->setText(QCoreApplication::translate("MainWidget", "\320\235\320\276\320\262\320\276\320\265 \320\264\320\265\321\200\320\265\320\262\320\276", nullptr));
        info_type->setTitle(QCoreApplication::translate("MainWidget", "\320\242\320\270\320\277", nullptr));
        info_1->setText(QCoreApplication::translate("MainWidget", "OX \321\206\320\265\320\275\321\202\321\200\320\260: ", nullptr));
        info_2->setText(QCoreApplication::translate("MainWidget", "OY \321\206\320\265\320\275\321\202\321\200\320\260: ", nullptr));
        info_3->setText(QCoreApplication::translate("MainWidget", "NUM \321\217\321\207\320\265\320\271\320\272\320\270 \320\277\320\276\321\207\320\262\321\213: ", nullptr));
        info_4->setText(QCoreApplication::translate("MainWidget", "\320\222\321\213\321\201\320\276\321\202\320\260: ", nullptr));
        info_6->setText(QCoreApplication::translate("MainWidget", "\320\241\320\262\320\265\321\202\320\276\320\273\321\216\320\261\320\270\320\262\320\276\321\201\321\202\321\214: ", nullptr));
        info_7->setText(QCoreApplication::translate("MainWidget", "\320\220\320\263\321\200\320\265\321\201\321\201\320\270\320\262\320\275\320\276\321\201\321\202\321\214: ", nullptr));
        info_8->setText(QCoreApplication::translate("MainWidget", "\320\222\320\273\320\260\320\263\320\276\320\273\321\216\320\261\320\270\320\262\320\276\321\201\321\202\321\214: ", nullptr));
        info_9->setText(QCoreApplication::translate("MainWidget", "\320\232\320\276\320\273-\320\262\320\276 \320\276\321\207\320\272\320\276\320\262 \321\200\320\276\321\201\321\202\320\260: ", nullptr));
        info_5->setText(QCoreApplication::translate("MainWidget", "\320\240\320\260\320\264\320\270\321\203\321\201: ", nullptr));
        info_10->setText(QCoreApplication::translate("MainWidget", "\320\234\320\260\320\272\321\201. \320\276\321\207\320\272\320\276\320\262 \321\200\320\276\321\201\321\202\320\260: ", nullptr));
        info_11->setText(QCoreApplication::translate("MainWidget", "\320\226\320\270\320\267\320\275\320\265\321\201\320\277\320\276\321\201\320\276\320\261\320\275\320\276\321\201\321\202\321\214: ", nullptr));
        info_12->setText(QCoreApplication::translate("MainWidget", "\320\234\320\260\320\272\321\201. \320\262\321\213\321\201\320\276\321\202\320\260: ", nullptr));
        info_0->setText(QCoreApplication::translate("MainWidget", "NUM: ", nullptr));
        info_13->setText(QCoreApplication::translate("MainWidget", "\320\234\320\260\320\272\321\201. \321\200\320\260\320\264\320\270\321\203\321\201: ", nullptr));
        info_00->setText(QCoreApplication::translate("MainWidget", "Type: ", nullptr));
        info_value->setTitle(QCoreApplication::translate("MainWidget", "\320\227\320\275\320\260\321\207\320\265\320\275\320\270\320\265", nullptr));
        i_1->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_2->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_3->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_4->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_6->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_7->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_8->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_9->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_5->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_10->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_11->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_12->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_0->setText(QCoreApplication::translate("MainWidget", "-1", nullptr));
        i_13->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        i_00->setText(QCoreApplication::translate("MainWidget", "-1", nullptr));
        info_name->setText(QCoreApplication::translate("MainWidget", " \320\230\320\275\321\204\320\276 \320\276 \321\200\320\260\321\201\321\202\320\265\320\275\320\270\320\270", nullptr));
        info_weather->setText(QCoreApplication::translate("MainWidget", " \320\230\320\275\321\204\320\276 \320\276 \320\277\320\276\320\263\320\276\320\264\320\265", nullptr));
        info_wvalue->setTitle(QCoreApplication::translate("MainWidget", "\320\227\320\275\320\260\321\207\320\265\320\275\320\270\320\265", nullptr));
        w_1->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        w_2->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        w_3->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        w_0->setText(QCoreApplication::translate("MainWidget", "-1", nullptr));
        info_wtype->setTitle(QCoreApplication::translate("MainWidget", "\320\242\320\270\320\277", nullptr));
        winfo_1->setText(QCoreApplication::translate("MainWidget", "\320\244\320\273\320\260\320\263 \320\277\320\276\320\263\320\276\320\264\321\213: ", nullptr));
        winfo_2->setText(QCoreApplication::translate("MainWidget", "\320\236\321\201\320\260\320\264\320\272\320\270 \320\267\320\260 1 \321\202\320\270\320\272: ", nullptr));
        winfo_3->setText(QCoreApplication::translate("MainWidget", "\320\222\321\200\320\265\320\274\321\217 \321\202\320\265\320\272\321\203\321\211. \321\201\320\276\321\201\321\202.:", nullptr));
        winfo_0->setText(QCoreApplication::translate("MainWidget", "\320\257\321\200\320\272\320\276\321\201\321\202\321\214 \321\201\320\276\320\273\320\275\321\206\320\260: ", nullptr));
        info_ftype->setTitle(QCoreApplication::translate("MainWidget", "\320\242\320\270\320\277", nullptr));
        finfo_1->setText(QCoreApplication::translate("MainWidget", "\320\232\320\276\320\273-\320\262\320\276 \320\276\320\261\321\212\320\265\320\272\321\202\320\276\320\262 \320\242\321\200\320\260\320\262\320\260: ", nullptr));
        finfo_2->setText(QCoreApplication::translate("MainWidget", "\320\232\320\276\320\273-\320\262\320\276 \320\272\321\203\321\201\321\202\320\276\320\262: ", nullptr));
        finfo_3->setText(QCoreApplication::translate("MainWidget", "\320\232\320\276\320\273-\320\262\320\276 \320\264\320\265\321\200\320\265\320\262\321\214\320\265\320\262: ", nullptr));
        finfo_0->setText(QCoreApplication::translate("MainWidget", "\320\232\320\276\320\273-\320\262\320\276 \321\217\321\207\320\265\320\265\320\272 \320\277\320\276\321\207\320\262\321\213: ", nullptr));
        info_forest->setText(QCoreApplication::translate("MainWidget", " \320\230\320\275\321\204\320\276 \320\276 \320\273\320\265\321\201\320\265", nullptr));
        info_fvalue->setTitle(QCoreApplication::translate("MainWidget", "\320\227\320\275\320\260\321\207\320\265\320\275\320\270\320\265", nullptr));
        fi_1->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        fi_2->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        fi_3->setText(QCoreApplication::translate("MainWidget", "0", nullptr));
        fi_0->setText(QCoreApplication::translate("MainWidget", "-1", nullptr));
        label->setText(QCoreApplication::translate("MainWidget", "TextLabel", nullptr));
        label_2->setText(QCoreApplication::translate("MainWidget", "TextLabel", nullptr));
        all_time_text->setText(QCoreApplication::translate("MainWidget", "\320\222\321\201\320\265\320\263\320\276 \320\262\321\200\320\265\320\274\320\265\320\275\320\270 \320\277\321\200\320\276\321\210\320\273\320\276 (\320\262 \321\202\320\270\320\272\320\260\321\205): 0", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWidget: public Ui_MainWidget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWIDGET_H
